mesh_files:
  base:
    visual:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/visual/base.dae
      material:
        name: "White"
        color: "1.0 1.0 1.0 1.0"
    collision:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/collision/base.stl

  shoulder:
    visual:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/visual/shoulder.dae
      material:
        name: "White"
        color: "1.0 1.0 1.0 1.0"
    collision:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/collision/shoulder.stl

  upperarm:
    visual:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/visual/upperarm.dae
      material:
        name: "White"
        color: "1.0 1.0 1.0 1.0"
    collision:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/collision/upperarm.stl

  forearm:
    visual:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/visual/forearm.dae
      material:
        name: "White"
        color: "1.0 1.0 1.0 1.0"
    collision:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/collision/forearm.stl

  wrist_1:
    visual:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/visual/wrist1.dae
      material:
        name: "White"
        color: "1.0 1.0 1.0 1.0"
    collision:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/collision/wrist1.stl

  wrist_2:
    visual:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/visual/wrist2.dae
      material:
        name: "White"
        color: "1.0 1.0 1.0 1.0"
    collision:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/collision/wrist2.stl

  wrist_3:
    visual:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/visual/wrist3.dae
      material:
        name: "White"
        color: "1.0 1.0 1.0 1.0"
    collision:
      mesh:
        package: elite_robots_description
        path: meshes/cs630/collision/wrist3.stl
